"""Fresh PostgreSQL migration

Revision ID: 2200cd095dfa
Revises: 
Create Date: 2025-04-09 06:42:21.262885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2200cd095dfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cold_storage_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.String(length=100), nullable=False),
    sa.Column('lastChecked', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cold_storage_wallets_address'), 'cold_storage_wallets', ['address'], unique=True)
    op.create_index(op.f('ix_cold_storage_wallets_id'), 'cold_storage_wallets', ['id'], unique=False)
    op.create_table('kraken_ledgers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refid', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('fee', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kraken_ledgers_refid'), 'kraken_ledgers', ['refid'], unique=False)
    op.create_index(op.f('ix_kraken_ledgers_time'), 'kraken_ledgers', ['time'], unique=False)
    op.create_table('kraken_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_pair', sa.String(), nullable=True),
    sa.Column('order_txid', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('fee', sa.String(), nullable=True),
    sa.Column('vol', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kraken_trades_time'), 'kraken_trades', ['time'], unique=False)
    op.create_table('kraken_wallets',
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.String(length=100), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('asset')
    )
    op.create_index(op.f('ix_kraken_wallets_asset'), 'kraken_wallets', ['asset'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_kraken_wallets_asset'), table_name='kraken_wallets')
    op.drop_table('kraken_wallets')
    op.drop_index(op.f('ix_kraken_trades_time'), table_name='kraken_trades')
    op.drop_table('kraken_trades')
    op.drop_index(op.f('ix_kraken_ledgers_time'), table_name='kraken_ledgers')
    op.drop_index(op.f('ix_kraken_ledgers_refid'), table_name='kraken_ledgers')
    op.drop_table('kraken_ledgers')
    op.drop_index(op.f('ix_cold_storage_wallets_id'), table_name='cold_storage_wallets')
    op.drop_index(op.f('ix_cold_storage_wallets_address'), table_name='cold_storage_wallets')
    op.drop_table('cold_storage_wallets')
    # ### end Alembic commands ###
