"""Initial schema

Revision ID: 79a444ea6cbf
Revises: 
Create Date: 2025-04-07 10:15:52.617174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a444ea6cbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cold_storage_wallets_address'), 'cold_storage_wallets', ['address'], unique=True)
    op.create_index(op.f('ix_kraken_ledgers_time'), 'kraken_ledgers', ['time'], unique=False)
    op.create_index(op.f('ix_kraken_trades_time'), 'kraken_trades', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kraken_trades_time'), table_name='kraken_trades')
    op.alter_column('kraken_trades', 'id',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_kraken_ledgers_time'), table_name='kraken_ledgers')
    op.alter_column('kraken_ledgers', 'id',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_cold_storage_wallets_address'), table_name='cold_storage_wallets')
    # ### end Alembic commands ###
