"""Add full ledger CSV fields

Revision ID: 923589fd7095
Revises: a721f620442b
Create Date: 2025-04-09 11:09:53.483633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923589fd7095'
down_revision: Union[str, None] = 'a721f620442b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraken_ledgers', sa.Column('txid', sa.String(), nullable=True))
    op.add_column('kraken_ledgers', sa.Column('subtype', sa.String(), nullable=True))
    op.add_column('kraken_ledgers', sa.Column('aclass', sa.String(), nullable=True))
    op.add_column('kraken_ledgers', sa.Column('wallet', sa.String(), nullable=True))
    op.add_column('kraken_ledgers', sa.Column('balance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraken_ledgers', 'balance')
    op.drop_column('kraken_ledgers', 'wallet')
    op.drop_column('kraken_ledgers', 'aclass')
    op.drop_column('kraken_ledgers', 'subtype')
    op.drop_column('kraken_ledgers', 'txid')
    # ### end Alembic commands ###
