"""Add refid to KrakenLedger

Revision ID: 97ff49a81cdb
Revises: 79a444ea6cbf
Create Date: 2025-04-07 18:53:51.411592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ff49a81cdb'
down_revision: Union[str, None] = '79a444ea6cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraken_ledgers', sa.Column('refid', sa.String(), nullable=True))
    op.alter_column('kraken_ledgers', 'id',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_kraken_ledgers_refid'), 'kraken_ledgers', ['refid'], unique=False)
    op.alter_column('kraken_trades', 'id',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kraken_trades', 'id',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_kraken_ledgers_refid'), table_name='kraken_ledgers')
    op.alter_column('kraken_ledgers', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('kraken_ledgers', 'refid')
    # ### end Alembic commands ###
