"""Update KrakenTrade model to include extended columns

Revision ID: ef65eb64848b
Revises: 2200cd095dfa
Create Date: 2025-04-09 08:37:50.038090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef65eb64848b'
down_revision: Union[str, None] = '2200cd095dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraken_trades', sa.Column('post_txid', sa.String(), nullable=True))
    op.add_column('kraken_trades', sa.Column('trade_type', sa.String(), nullable=True))
    op.add_column('kraken_trades', sa.Column('order_type', sa.String(), nullable=True))
    op.add_column('kraken_trades', sa.Column('price', sa.String(), nullable=True))
    op.add_column('kraken_trades', sa.Column('margin', sa.String(), nullable=True))
    op.add_column('kraken_trades', sa.Column('misc', sa.String(), nullable=True))
    op.add_column('kraken_trades', sa.Column('trade_id', sa.Integer(), nullable=True))
    op.add_column('kraken_trades', sa.Column('maker', sa.Boolean(), nullable=True))
    op.add_column('kraken_trades', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraken_trades', 'raw_data')
    op.drop_column('kraken_trades', 'maker')
    op.drop_column('kraken_trades', 'trade_id')
    op.drop_column('kraken_trades', 'misc')
    op.drop_column('kraken_trades', 'margin')
    op.drop_column('kraken_trades', 'price')
    op.drop_column('kraken_trades', 'order_type')
    op.drop_column('kraken_trades', 'trade_type')
    op.drop_column('kraken_trades', 'post_txid')
    # ### end Alembic commands ###
